### ISSUE TITLE
heatmapPEI seems to not work woth {}

### ISSUE THREAD

**Issue by BastienGamboa** [zhilongjia/cogena#2]
Hi,

I wanted to use a for loop to create a dedicated .jpg file for each cluster I had done with coExp, but the {} seems to not allows the graph production of heatmapPEI.
The following is an example:
`source("https://bioconductor.org/biocLite.R")
biocLite("cogena")
require(cogena)
data(Psoriasis)
clen_res <- clEnrich(coExp(DEexprs, nClust=2, clMethods="kmeans",  metric="correlation", method="complete", ncore=2, verbose=TRUE),
                     annofile=system.file("extdata", "c2.cp.kegg.v5.0.symbols.gmt.xz",  package="cogena"), sampleLabel=sampleLabel)

jpeg(file="_Test.jpg", width=10, height=8, units="in", res=150)
heatmapPEI(clen_res, "kmeans", "2") # jpg file good
dev.off()

{
jpeg(file="_Test2.jpg", width=10, height=8, units="in", res=150)
heatmapPEI(clen_res, "kmeans", "2")
dev.off() # white jpg file
}`

(Sorry for the R code not colored, I do not know how to do it here).

Thank you for the answer,
Bastien

**Comment by zhilongjia** [comment]
solution: using `print` to explicitly plot it as `heatmapPEI` called `ggplot2`. 
ref:  http://stackoverflow.com/questions/15678261/r-ggplot-does-not-work-if-it-is-inside-a-for-loop-although-it-works-outside-of
