### ISSUE TITLE
Error in annotation [genenames,j] : subscript out of bounds (Enrichment analysis)

### ISSUE THREAD

**Issue by nandhinik2** [zhilongjia/cogena#3]
While running the below code
<gds3952 <- getGEO('GDS3952')
eset <- GDS2eSet(gds3952, do.log2=TRUE)
fa <- factor(pData(eset)$disease.state)
DExprs1 <- subset(DExprs,select=c("ID","adj.P.Val","P.Value","F","Gene.symbol","Gene.title"))
DExprs1
library(cogena)
ls()
annoGMT2 <- "c5.bp.v5.0.symbols.gmt.xz"
annoGMT <- "c2.cp.kegg.v5.0.symbols.gmt.xz"
annofile <- system.file("extdata", annoGMT, package="cogena")
annofile2 <- system.file("extdata", annoGMT2, package="cogena")
nClust <- 3
sampleLabel <- factor(sampleLabel,levels=c("bba", "ec","mbc","h","presm","posm"))
sampleLabel <- factor(sampleLabel,levels=c("bba", "ec","mbc","h","presm","posm"))
ncore <- 2
clMethods <- c("hierarchical","pam")
metric <- "correlation"
method <- "complete"
genecl_result <- coExp(DExprsr1, nClust=nClust, clMethods=clMethods, 
                       metric=metric, method=method, ncore=ncore)
summary(genecl_result)
**clen_res <- clEnrich(genecl_result, annofile=annofile, sampleLabel=sampleLabel)**
>
Getting Error as
  <Error in annotation [genenames,j] : subscript out of bounds>

**Comment by zhilongjia** [comment]
Only gene symbols, not probe id are acceptable as these gene sets use them too.
