### ISSUE TITLE
downloaded drugsig data for about 500 down regulated drug compressed it by xz but give this error

### ISSUE THREAD

**Issue by puneetvaza** [zhilongjia/cogena#5]
`cmapDn100_cogena_result <- clEnrich_one(genecl_result, "pam", "10",  annofile=system.file("extdata", "down12.gmt.xz", package="cogena"),  sampleLabel=sampleLabel)`

Error in pei[as.character(k), ] <- cogena::PEI(genenames, annotation = annotation,  : 
  number of items to replace is not a multiple of replacement length

**Comment by puneetvaza** [comment]
#metformi	500	PRKD1	ZNF407	ZEB2	CTH	PLXNC1	SLC4A7	SRI	ATRNL1	UTP14A	TNFRSF11B	LRRC8B	C8orf4	FRZB	ZNF135	NOVA2	DPT	KITLG	UHRF1BP1L	IGK///IGKC	ALG13	RARRES1	ZNF711	TMEM47	CDK11A///C	DBT	IGHV4-31//	IGJ	EPB41L3	CR1	SLC17A6	RHEB	EDNRB	PTPN2	GPR4	CDH4	XKRY2///XK	PPP1R3A	KCNG1	MBNL1	NCLN	PTGDR	RBBP4	TRAPPC13	LRP12	ANTXR1	CATSPERB	PCDHGB6	MSTN	EFCAB11	CNGB1	SLCO1A2	DIAPH2	TYMP	CLCA2	EXOSC1	PRR5L	N6AMT1	ABCG5	AKIRIN2-AS	PKD2L2	HMGN5	COL1A1	SLC2A3	ABCA1	ITGA4	FABP1	CASP1	DSC3	SLC22A2	XYLB	NR2F1	MSC	CLN5	ELK4	CD72	MUC4	OVOL1	NAB1	LPHN3	SMAD6	REM1	KYNU	BICC1	HIST1H2AK	POLR2J3///	HYMAI	ASPN	TSPAN12	ELOVL4	LRP12	GPR22	FCHSD2	MVK	IL11RA	IL12B	CABP1	POU3F3	ART3	CHN2	HLA-DQB1	ZNF780A///	TLE4	IFT74	ETFDH	FAM63B	PLCB4	KLF12	IL12RB2	RPE65	P2RY1	PAX8	DAZ4///DAZ	CPQ	HPX	NOX1	STK3	MST1L///MS	CTDSPL	RBM4	OPCML	NCAM1	DENND5B	SEC24D	POU2F3	PCLO	CXCR3	SORBS1	FAT4	ACSM5	MCTP1	HOXC8	HLA-E	B4GALT1	LOXL2	ZNF254	CES1	NFE2	NKX2-1	NEK1	TRPM3	NPAT	LOC1001338	SAT1	MUC5AC	GPR65	RIMS2	EPHA5	CROCC	CFAP74	C13orf41	PAH	HMP19	LRP1B	TMEM255A	GID4	LAMA1	RGS1	AFAP1	GAP43	GATA4	LAMP3	ITIH3	TNK1	MOG	SNURF///SN	ASMT	RIPPLY3	SHH	ASB4	HLA-DQB1	PTPRJ	PML	ZEB1	ME1	INTS1	AKAP13	COX11	ALB	ZNF674	LOC1002891	SMPD1	ITPR1	CYB5A	C14orf93	CNTNAP2	CCDC28B	EBLN2	XAGE1B///X	ANTXR1	ZBTB32	CA8	WDR19	ZNF318	TGM1	CEACAM7	ZKSCAN7	FRMPD1	GYPE	SLC39A8	SWAP70	MYCN	TEKT2	KLRD1	CDC14A	GRIA1	RGS11	PCDHGA3///	HIST1H2AE	PIAS2	NFASC	ZNF780B	APOBEC3F//	DOCK9	PIGC	ANKRD53	ABCA1	LRRN2	MASP2	KMT2B	FDPS	LINC00667	SLC6A2	EIF1	TLR7	LRRC37A4P	OBP2A///OB	CDADC1	NEFL	GSAP	FAM13A	PAFAH2	EPHA3	CERS1///GD	HTN1	CRYBB2P1//	SCN9A	SMAD6	MAGEA1	PITX2	CRISP3	ADAM28	IL33	MR1	TRIM23	GPER1	PHACTR1	LOC1005105	HSD3B1	SOS2	ZNHIT2	KDM4D	KERA	ADARB2	GREM2	PIDD1	LZTS1	VIM	ENG	C1QB	DZIP1	CDA	CNTRL	SIGLEC6	MYH8	PDE6H	ALDH1A2	PYY	CDH12	INE1	ESRRG	PSD	FOXE1	LOC1002900	HIST1H4J//	IGHM	EFNB3	EDA	CSF2RA	NDUFB7	PTPRN2	ESR1	ANKRD12	ALDH7A1	SAP30	ZFPL1	SMR3A	AZU1	HIST1H4I	KIAA1614	CEP41	IGHMBP2	FRMD4B	C10orf12	LOC1002870	ZNF639	DYSF	PALMD	ADM2	TCEB3B	PPP2CB	SEPP1	ANK2	MED1	ACTN2	DZIP1	MMP19	WIF1	HSD17B2	TLR2	CLEC3B	ZSCAN12	SIGLEC7	APOF	SPAG11B	ATP2A3	HIST1H2BL	CALCR	ELAVL2	HUWE1	EHD1	KHDRBS3	AQP4	CDC14A	CAMKK2	SARDH	ZKSCAN4	SLC25A42	IFI44	TPH1	SNX29P2	EXT1	PRKCA	RTCA	STRN3	CFAP70	IQCK	GTPBP10	MUC7	IGLV1-40//	TGM4	HPS4	AMDHD2	EMCN	GREB1L	CRYBB2P1	KLHL22	ZDHHC8P1	HSPA6	SERPING1	KDM5B	IL10RA	MATN1	SIRPB1	CDH9	SPRR2B	LGALS8	COL6A2	NMNAT2	ZNF589	IGFBP3	SND1-IT1	RAD51B	ANXA2P1	ORC5	RUNDC3A	CCPG1	MAGEA6	NUP54	DUOX1	PARVB	CYP2A7P1	PTPRB	CXCL14	CCDC88A	COL4A3BP	TTC21B	LRRC19	ADAMTS7	LEF1	CDC5L	ID2	HPGD	FPR1	WNT2	CLC	SERPINA6	AGTR2	ADAM20	MOGAT2	LPAL2	ERC2-IT1	P2RX3	ADH1B	RGS12	ERAP1	CCL23	ITSN1	ZNF493	VCAN	LOC1002879	SEPT6	TJP3	MAGED2	TSFM	CT62	GPX5	CTAGE5	NLRP3	TM6SF2	ZC3H7B	IGLV3-19	RPS14	SCUBE3	PARVA	C10orf88	TRIM68	ANKH	KPTN	EMP1	CTDSPL	TMOD1	SGSH	SLC16A4	ACSM3	MIS18BP1	P2RY14	HPGDS	MTHFR	LDHC	PTGFR	RNF185	CAMKK2	RFC1	ADRB1	HLA-DRA	SYK	RALGPS1	KLHL20	ZNF257	KHK	FGFR2	PDC	TTC9	PPFIA3	GGA2	HIST1H2AM	ALPK3	GK3P	ARL15	LINC00472
#metformi	500	SLC4A7	KCTD12	MST1L///MS	GPR98	HSD3B1	CR1	TSPAN12	GIMAP6	LOC284244	FLG	RAB7A	SCUBE3	PRR5L	EML2	ZNF711	WDR18	MED8	OPCML	PIWIL1	ANKRD12	ZBTB32	RGS17	UTP14A	KLF9	MAP3K8	DSC3	PYY	AKR1C4	TIMM8A	SDC2	SST	HIST1H2BC	BUB1	NPAS3	EMP1	OMG	GAB1	CDH12	RNF6	TTC9	CD72	CYP2A7P1	CNTNAP2	SULT1E1	AIM1L	PKD2L2	GBP1	RCAN2	RARRES1	SGCG	SLC43A3	SARDH	GLYR1///SE	RND2	KCND3	SLC6A2	FAM188A	C8orf4	CCDC85C	TEX13A	KDM6A	CEP104	GAP43	SAP30	ITGB8	TDGF1P3///	NOVA2	GAGE12D///	PDE6H	CDH4	ZFP69B	APOF	ADRB1	PCK1	TFPI2	EFEMP2	ADCY2	SERPINB1	FAM169A	SOCS7	GYS2	SRCAP	ITPR1	DYSF	TIMM22	C1orf54	KCNMA1	HPGD	PCDH7	CHRNB4	PAX3	SAP18	HFE	SLC35D2	TMCO6///IK	ALDH7A1	GGA2	ACOT11	ZNF287	KLF11	ANTXR1	LRP12	PDPN	FAHD2A	ADAM22	NPAS1	CALCR	ADAM22	RGS12	SOCS5	PPP1R3A	LHX2	ITGB3	MICAL3	KDM6B	MLLT4	KIAA1614	SORBS1	NIN	PHF20L1	RETN	UGT1A9///U	HMGN5	SULT1A4///	C14orf1	STK17A	ORC4	ALOX5	MPPED2	EXOG	DSC1	FOXH1	XKRY2///XK	DDX17	TFPI2	TRAPPC10	IL1RAP	ZNF493	PADI4	EPB41L3	FRMD4B	PDLIM5	ETAA1	ACSM5	FAM110D	ZNF407	UCHL1	MED1	FCHSD2	CD37	EDNRB	DBT	DGKG	CHRNA4	ALX1	CRTAM	CAMKK2	AQP4	PTPRJ	KMO	ESR1	PTCRA	PARD6B	PHACTR1	DUSP7	PIGC	CBX2	FABP3P2	SPN	LOC1002870	PLEKHO1	SCUBE2	HPSE	LOXL2	CDK10	SGSH	LZTS3	ZNF354A	CNTRL	CPEB3	ZNF571	IL15RA	XYLB	URB1	CRYAA	PSIP1	ORC5	EZH1	ASTN1	MAPRE2	C1orf95	UPK1A	ZNF550	ABCA1	HCRP1	SYNJ2	TM6SF2	MUC7	IGLV1-40//	LINC00667	FHL3	CLSTN2	RIN3	DECR2	XAGE1B///X	AKIRIN2-AS	ADARB2	MED18	EIF3F	PPP2CB	MMP1	CGA	NOX1	RPE65	SHH	DDX3X	LGALS8	TNFSF13	TRIM5	IFNA2	GHRHR	HLA-DPA1	GLTSCR1L	OBSL1	PPFIBP1	HSPA12A	XYLB	IGHM///IGH	ST14	MASP2	SOS2	ZNF750	USP49	PTEN	C9orf156	SAA3P	KCNE4	DNAJB9	PTPRM	DSCR3	TK2	KCNH1	RFC1	CSDC2	MTAP	SH3GL3	CEBPE	IFT74	TMEM127	KDM5B	TPD52	PNLIP	GABPB1	CNGA1	SCN4A	MAGEB3	PPIL2	DEAF1	CLTC	LSS	ME1	ERG	ARL3	G0S2	RAD23B	HIST1H4I	XRCC6	ZCCHC14	CYB5A	TGM4	PTMS	TMEM70	ANKH	GREB1L	A4GNT	C3orf36	OR10J1	CCS	BCAS1	TLR2	CREB5	PRG4	TNFAIP6	LHX1	CELA2A///C	CRYBB2P1//	KLF12	SLC17A4	AGTR2	CNGB1	CABP1	STAT3	RORA	GCNT2	PDLIM5	PDE4A	FYN	ZFP36L1	ATXN7L1	CFTR	ZNF277	LRRN2	MYH7	CYP2A7P1	OR2F2	FXYD6	ATHL1	MTMR8	DENND2A	ING4	TRAK1	CPSF6	UMPS	AFAP1	ALOX5AP	PMAIP1	HDAC9	ZMYND10	CEP162	PPIL2	CXCR5	GCM1	SNRK	GYPE	UTF1	PPAP2B	ARHGEF6	RGS20	SGCD	GYG2	NF1	EDA	DBT	CHN2	RECQL5	POP1	DDX28	SMARCA4	HIST1H1B	PLD1	GK3P	FRMD4B	MAGEC3	MUL1	TMEM57	RAB3IL1	COLEC11	EBLN2	MAP9	SCRT1	TUBBP5	FAM168A	RHEB	PPP2R1B	RALGPS1	SNCA	MMP19	BMP5	PAK2	RIMS2	GDF10	C9	BTC	RARS2	KCNC4	DAZ4///DAZ	GPR39	NFE2	LILRB2	NUP214	OGFR	PCDHGA3///	RBL2	RMND5A	MEG3	HLA-DQB1	EMID1	HIST1H2BO	KIR3DX1	PIK3R4	ZNF639	FER1L4	PRRG3	C21orf2	ARHGEF26	TBC1D2	CALML4	ACSL4	CHKB	GNA11	SCN3B	IL11RA	MBNL2	GPA33	LDB2	ASGR1	GH1	RGS5	LPHN3	NR5A2	ASMT	NOX1	TRIM14	CSTF2T	TRMU	SENP6	ITGB3	OGG1	HYMAI	RAPGEF2	KMT2B	SMNP	RAPGEFL1	TNFRSF21	SUV39H2	CCR10	TRMT44	APOL2	NCR2	GSTA3	ARHGAP35	TTLL4	EDNRA	XRCC4	EXOG	PAX5	SCN9A	HS6ST1	MSTN	THEMIS2	BEST1	DMD	TRPV5	IGHM	FAM65B	NFKBIL1	DYRK3	MTSS1	ADRA1D	FCAR	TAF6L	DENND5B	ATP9A	KMT2A	MT4	MAG	RGCC	C14orf93	C22orf46	CEP97	CCDC33	OR11A1	ABHD2	ENO2	CTDSPL	CASP3

**Comment by puneetvaza** [comment]
for (k in sort(unique(cluster))) { genenames <- names(which(cluster == k)) pei[as.character(k),] <- cogena::PEI(genenames, annotation = annotation, annotationGenesPop = annotationGenesPop) }
 Error in pei[as.character(k), ] <- cogena::PEI(genenames, annotation = annotation,  :    number of items to replace is not a multiple of replacement length

**Comment by zhilongjia** [comment]
Guess the probelm is file `"down12.gmt.xz"`. Check the existence and format? Thank you.
