### ISSUE TITLE
Hello, I would like to ask how to build sampleLabel。

### ISSUE THREAD

**Issue by limingxiang** [zhilongjia/cogena#6]
您好！I built a sampleLabel with your data, the first column is samplename, the second column is type, and then read into the file using read.csv(), but directly using ：samplela <- factor(sample, levels=c("ct" , "Psoriasis")) ，there will be an error in the following run, how to build sampleLabel?
>sample <- read.csv("sample.csv",head = T)
>head（sample）
       name type
1 GSM337261   ct
2 GSM337262   ct
3 GSM337263   ct
4 GSM337264   ct
5 GSM337265   ct
6 GSM337266   ct
>samplela <- factor(sample, levels=c("ct", "Psoriasis"))
> samplela
name type 
<NA> <NA> 
Levels: ct Psoriasis
非常感谢您！R语言新手，希望能给解决下！

**Comment by zhilongjia** [comment]
variable `sample` should be a vector, instead of data.frame.
