### ISSUE TITLE
Error in annotation

### ISSUE THREAD

**Issue by IyadSultan** [zhilongjia/cogena#7]
Hello dear,

I am getting this error

clen_res <- clEnrich(genecl_result, annofile=annofile, sampleLabel=sampleLabel)
Note: 716 out of 773 exist in the genes population. 
**Error in annotation[genenames, j] : subscript out of bounds**

Although I converted GENE.IDs to SYMBOLS:
library(annotate)
library(org.Hs.eg.db)
getSYMBOL(tT$Gene.ID, data='org.Hs.eg')->geneNames

geneNames[1:20]
 [1] "NFATC2IP" "PLAG1"    "FRMD8"    "ANXA4"    "HAUS2"    "FBXO4"   
[7] "NIF3L1"   "QRSL1"    "IFNAR1"   "P2RX5"    "TUBA1A"   "ZNF106"  
[13] "CASP8"    "ACTR8"    "MSMO1"    "PRG2"     "CRB1"     "CABLES1" 
[19] "DIPK2B"   "DOCK1"

**Comment by zhilongjia** [comment]
Try to use the newest version by `devtools::install_github("zhilongjia/cogena")`. 
If the problem still, please send a small runnable example to reproduce this error. Thank you.

**Comment by IyadSultan** [comment]
Fixed thank you
