### ISSUE TITLE
Which cluster to choose

### ISSUE THREAD

**Issue by IyadSultan** [zhilongjia/cogena#8]
Hello dear,

I am looking for pathways involved in viral infection.  Actually all KEGG categories listed are involved in viral infection.  Which one of these gene clusters would you choose for drug repositioning?
![Picture1](https://user-images.githubusercontent.com/42122545/75484257-14b96800-59b1-11ea-81f7-1edbb189164a.png)

**Comment by zhilongjia** [comment]
Hi IyadSultan, I cannot see the picture. you can try each cluster to check if there are some known anti-virus drugs on the list. Email me (zhilongjia#gmail.com; replace # with @) if more detailed questions and pictures. Thank you.

**Comment by zhilongjia** [comment]
I suggest that decreasing the number of clusters as there were so many non-pathway-enriched clusters. I see your picture today finally, though unclear.

**Comment by IyadSultan** [comment]
![000009](https://user-images.githubusercontent.com/42122545/75613904-6857bd00-5b3b-11ea-8eaf-99e428d53898.png)

Thank you very much for your reply!
This is the new graph with 5 clusters.  
Which one of these clusters is most suitable?
Is it wrong if I just use Up or Down genes as a whole?
Is there away I can get the names of the drugs?  I have to copy them manually now.

Many thanks in advance.

**Comment by zhilongjia** [comment]
![image](https://user-images.githubusercontent.com/1230436/75774424-f1186800-5d8a-11ea-92f8-d313ecb9494f.png)
due to the network, I cannot see your figure. send an email, please. Thank you.
