### ISSUE TITLE
error with clEnrich parameter sampleLabel

### ISSUE THREAD

**Issue by heylookabed** [zhilongjia/cogena#9]
Hello.
I have been following the tutorial and have named my variables after the ones listed in Data(Psoriasis).
Despite using the same names for the variables, I had to specify clMethods to get coExp to work ("hierarchical").
When I run clEnrich, I get the following error:
Error in clEnrich(genecl_result, annofile = annofile, sampleLabel = sampleLabel) : 
  No name for parameter sampleLabel.

Any ideas on what might cause this?
Unlike the example data, I am trying to differentiate between 3 groups (NL, PT, PM) as opposed to the 2 used in the example.

I have posted the code I am using as well my input file for the expression data.
[cogena_input.zip](https://github.com/zhilongjia/cogena/files/5200334/cogena_input.zip)

library(cogena)
setwd("C:/Users/omics_IPA/Documents/")
data<-c("NL","NL","NL","NL","NL","PT","PT","PT","PT","PT","PT","PT","PT","PT","PT","PT","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM","PM")
data_DEP=read.csv("cogena_input.csv")
sampleLabel=factor(data,levels=c("NL","PT","PM"))
DEexprs=as.matrix.data.frame(data_DEP);
rownames(DEexprs)<-DEexprs[,1]
DEexprs<-DEexprs[,-1]

# Clustering the gene expression profiling
clMethods <- c("hierarchical","kmeans","diana","fanny","som","model","sota","pam","clara","agnes")
genecl_result <- coExp(DEexprs, nClust=5:6, clMethods="hierarchical", metric="correlation", method="complete", ncore=2, verbose=TRUE)

# Gene set used
annofile <- system.file("extdata", "c2.cp.kegg.v5.0.symbols.gmt.xz", package="cogena")

# Enrichment analysis for clusters
clen_res <- clEnrich(genecl_result, annofile=annofile, sampleLabel=sampleLabel)

**Comment by zhilongjia** [comment]
if you check the variable `sampleLabel` in my `data(Psoriasis)` example, you will see there are names for the values in the vector sampleLabel. This is the error alerted, "No name for parameter sampleLabel.".

see figure below.
![20201101162233](https://user-images.githubusercontent.com/1230436/97798194-c3a7f500-1c5e-11eb-8429-33c5ad0d7c5e.png)
